// Typing passages are excerpts from Wikipedia, used under CC BY-SA 4.0 (modified:
// trimmed to single paragraphs and normalised to plain ASCII). See the full
// attribution and source-article list at /quotes-credits.html.
//
// There are ~3000 of them, so they live in /public/quotes.json and are fetched
// at runtime (kept out of the JS bundle) and loaded before the app mounts
// (see main.ts). Components keep importing `quotes` and using it synchronously.

export interface Quote {
  text: string
  source: string
  url?: string
}

export const quotes: Quote[] = []

// Traditional Chinese (Taiwan) passages — /quotes-zh.json, generated by
// scripts/generate-zh-quotes.py from zh.wikipedia (zh-tw variant), restricted
// to the MOE 4808 common characters + digits + a small punctuation set.
export const quotesZh: Quote[] = []

let loading: Promise<void> | null = null

function fetchInto(url: string, target: Quote[], clean: (t: string) => string): Promise<void> {
  return fetch(url)
    .then((r) => {
      if (!r.ok) throw new Error(`HTTP ${r.status}`)
      return r.json()
    })
    .then((data: Quote[]) => {
      const cleaned = data.map((q) => ({ ...q, text: clean(q.text) }))
      target.splice(0, target.length, ...cleaned)
    })
    .catch((err) => {
      console.error(`Failed to load ${url}`, err)
    })
}

export function loadQuotes(): Promise<void> {
  if (!loading) {
    loading = Promise.all([
      // A passage must never start with punctuation/whitespace, otherwise the
      // very first thing you'd have to type is a stray symbol (e.g. a leading
      // quote mark, dash, or bracket). Drop any leading non-alphanumeric run so
      // typing always begins on a real word. Texts are normalised to ASCII.
      fetchInto('/quotes.json', quotes, (t) => t.replace(/^[^A-Za-z0-9]+/, '')),
      // Chinese passages are already guaranteed by the generator to open on a
      // real character, so no cleaning is needed.
      fetchInto('/quotes-zh.json', quotesZh, (t) => t),
    ]).then(() => undefined)
  }
  return loading
}
